language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

before_script:
  - composer update --no-interaction --no-suggest

script:
  - composer test

notifications:
  email:
    - prager.adam87@gmail.com
