language: php

php:
  - 5.5
  - 7.0

matrix:
  fast_finish: true

before_script:
  - composer update --dev

script: phpunit

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - prager.adam87@gmail.com
