language: php

php:
  - 8.0
  - 8.1

matrix:
  fast_finish: true

before_script:
  - composer update --no-interaction --no-suggest

script:
  - composer test

notifications:
  email:
    - prager.adam87@gmail.com
